### ISSUE TITLE
Create Orders Page

### ISSUE THREAD

**Issue by Drakeoon** [AlanPieczonka/fast-food-frontend#10]
## Todo:
- [x] Create components to display existing orders
- [x] Add ability to complete order
- [x] If the order is left for longer than 5 minutes, a notification should appear
- [x] Allow to drag & drop order cards
