### ISSUE TITLE
Create Management page

### ISSUE THREAD

**Issue by Drakeoon** [AlanPieczonka/fast-food-frontend#11]
## Todo:
- [x] The management page should show a full-screen view of items in the application
- [x] User should be able to set theme primary color as well as upload brand logo
- [x] User should be able to select a dark theme
- [x] On item click there should appear a modal which allows you to modify item's properties: price, title, description, image, out/in stock
- [x] There should also be a switch to make product out of stock (active: true/false or something like that)
