### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by Drakeoon** [AlanPieczonka/fast-food-frontend#12]
## Todo
- [x] User is able to toggle cards variations display
- [x] User is able to select quantity and add to the cart
- [x] User is able to remove from cart
- [x] User is able to update quantity in the cart
- [x] User is able to complete order, which will show a mocked payment process and create a new order
