### ISSUE TITLE
Websocket functionalities

### ISSUE THREAD

**Issue by Drakeoon** [AlanPieczonka/fast-food-frontend#13]
## Todo
- [ ] Notify everyone about new order
- [ ] Notify everyone about order being ready to serve
- [ ] Notify everyone about product properties modification
- [ ] Notify everyone about re-stock
